# cyborg
statarb signal research playground

In [1]:
import matplotlib
try:
    matplotlib.use('module://ipympl.backend_nbagg')
except Exception:
    pass  # falls back to inline — hover won't work but charts still render

import os
import sys
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd
import numpy as np
import psycopg
from utils.viz import Viz

pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

In [2]:
DB_DSN = os.getenv("DB_DSN", "postgresql://benjils:snickers@raptor:5432/markets")
conn = psycopg.connect(DB_DSN)

## headline UST yields

In [27]:
# pull current on-the-run nominal yields
query = """
SELECT h.*, s.auction_date, s.issue_date, s.maturity_date
FROM md.headline h
left join sec.auctioned_securities s on s.cusip = h.cusip
WHERE asset_class = 'nominal'
  AND status = 'c'
ORDER BY ts, tenor
"""

raw = pd.read_sql(query, conn)
raw['ts'] = pd.to_datetime(raw['ts'])
print(f"{len(raw):,} rows | {raw['ts'].min().date()} to {raw['ts'].max().date()}")
raw[raw['yld_ytm_mid']>10].tail(10)

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_60065/2179807548.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  raw = pd.read_sql(query, conn)

61,426 rows | 1990-01-02 to 2026-02-03

,ts,tenor,asset_class,cusip,status,px_last,yld_ytm_mid,auction_date,issue_date,maturity_date
41549,2020-02-26,5-Year,nominal,912828ZC7,c,1.1836,146.1000,2020-02-26 05:00:00+00:00,2020-03-02 05:00:00+00:00,2025-02-28 05:00:00+00:00
42209,2020-05-27,5-Year,nominal,912828ZT0,c,0.3242,175.7400,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00
52092,2023-04-26,5-Year,nominal,91282CHA2,c,3.4570,127.2550,2023-04-26 04:00:00+00:00,2023-05-01 04:00:00+00:00,2028-04-30 04:00:00+00:00

In [32]:
raw[(raw['tenor']=='5-Year')&(raw['ts']>='2020-05-20')&(raw['ts']<='2020-06-02')]

,ts,tenor,asset_class,cusip,status,px_last,yld_ytm_mid,auction_date,issue_date,maturity_date
42149,2020-05-20,5-Year,nominal,912828ZL7,c,100.1523,0.3440,2020-04-27 04:00:00+00:00,2020-04-30 04:00:00+00:00,2025-04-30 04:00:00+00:00
42162,2020-05-21,5-Year,nominal,912828ZL7,c,100.1523,0.3440,2020-04-27 04:00:00+00:00,2020-04-30 04:00:00+00:00,2025-04-30 04:00:00+00:00
42175,2020-05-22,5-Year,nominal,912828ZL7,c,100.1914,0.3360,2020-04-27 04:00:00+00:00,2020-04-30 04:00:00+00:00,2025-04-30 04:00:00+00:00
42183,2020-05-25,5-Year,nominal,912828Z52,c,104.8945,0.3210,2020-01-27 05:00:00+00:00,2020-01-31 05:00:00+00:00,2025-01-31 05:00:00+00:00
42196,2020-05-26,5-Year,nominal,912828ZL7,c,100.1328,0.3480,2020-04-27 04:00:00+00:00,2020-04-30 04:00:00+00:00,2025-04-30 04:00:00+00:00
42209,2020-05-27,5-Year,nominal,912828ZT0,c,0.3242,175.7400,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00
42222,2020-05-28,5-Year,nominal,912828ZT0,c,99.5586,0.3390,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00
42235,2020-05-29,5-Year,nominal,912828ZT0,c,99.7227,0.3060,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00
42248,2020-06-01,5-Year,nominal,912828ZT0,c,99.7070,0.3090,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00
42261,2020-06-02,5-Year,nominal,912828ZT0,c,99.6523,0.3200,2020-05-27 04:00:00+00:00,2020-06-01 04:00:00+00:00,2025-05-31 04:00:00+00:00

In [29]:
# pivot to wide format: date x tenor
yields = raw.pivot(index='ts', columns='tenor', values='yld_ytm_mid')

# clean up tenor ordering
tenor_order = ['2-Year', '3-Year', '5-Year', '7-Year', '10-Year', '20-Year', '30-Year']
yields = yields[[c for c in tenor_order if c in yields.columns]]
yields.columns = [c.replace('-Year', 'Y') for c in yields.columns]

print(f"shape: {yields.shape}")
# print(yields.max())
yields[yields['5Y']>100].tail()

ValueError: Index contains duplicate entries, cannot reshape

In [5]:
# headline yield curves
v = Viz()
v.line(yields, title='On-the-Run UST Yields', yaxis_title='Yield (%)')

VBox(children=(HTML(value='<b style="font-size:13px; color:#333;">ON-THE-RUN UST YIELDS</b>'), HBox(children=(…

## spreads & butterflies

In [ ]:
spreads = pd.DataFrame(index=yields.index)
spreads['2s10s'] = yields['10Y'] - yields['2Y']
spreads['2s30s'] = yields['30Y'] - yields['2Y']
spreads['5s30s'] = yields['30Y'] - yields['5Y']
spreads['2s5s10s'] = 2 * yields['5Y'] - yields['2Y'] - yields['10Y']

# convert to bps
spreads = spreads * 100

v.line(spreads[['2s10s', '2s30s', '5s30s']], title='UST Curve Spreads', yaxis_title='bps')

In [ ]:
v.line(spreads[['2s5s10s']], title='2s5s10s Butterfly', yaxis_title='bps')

## daily changes & basic stats

In [ ]:
chg = yields.diff() * 100  # daily change in bps

chg.describe().round(2)

In [ ]:
# rolling correlations
v.rolling_corr(chg, col1='2Y', col2='10Y', window=60, title='2Y vs 10Y Daily Change Correlation (60d)')

In [ ]:
# correlation heatmap of daily yield changes
v.corr_heatmap(chg.dropna(), title='UST Daily Yield Change Correlations')

## z-scores

In [ ]:
# rolling z-scores of spread levels
v.rolling_zscore(spreads['2s10s'], window=120, title='2s10s Z-Score (120d)')

In [ ]:
v.rolling_zscore(spreads['2s5s10s'], window=120, title='2s5s10s Butterfly Z-Score (120d)')

---
## scratch

In [ ]:
conn.close()